name: Pulumi CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the code

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your Python version

      # Install Python and Pulumi dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pulumi
          # Install additional dependencies if needed
          # pip install -r requirements.txt  # Uncomment if you have a requirements file

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up the Cloud SDK with the project ID
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Deploy the Pulumi program
      - name: Deploy with Pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: LuisRiosAcloud/pulumi-project/dev
          work-dir: pulumi-project
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
