name: Pulumi CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the code

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your Python version

      # Install Python and Pulumi dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pulumi
          # Install additional dependencies if needed
          # pip install -r requirements.txt  # Uncomment if you have a requirements file

      # Install Pulumi CLI
      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          # Add Pulumi to the current PATH for the next steps
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      # Verify Pulumi installation (check if it's working)
      - name: Check Pulumi version
        run: pulumi version

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up the Cloud SDK with the project ID
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Deploy the Pulumi program
      - name: Deploy with Pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: iacP/prueba01/dev1
          work-dir: prueba01
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

