name: Deploy Pulumi to GCP

on:
  push:
    branches:
      - main  # Ejecutar cuando haya un push en la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v3.0.1
      with:
        pulumi-version: 3.x  # Asegúrate de usar la versión adecuada

    - name: Install project dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Configure GCP credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project rip-gti-desa

    - name: Pulumi preview
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi preview

    - name: Pulumi up
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi up --yes